export const tourInfo = [
  {
    key: 1,
    date: '17 Nov 2022',
    city: 'PERTH',
    venue: 'Astor Theatre',
  },
  {
    key: 2,
    date: '18 Nov 2022',
    city: 'PERTH',
    venue: 'Astor Theatre',
  },
  {
    key: 3,
    date: '21 Nov 2022',
    city: 'ADELAIDE',
    venue: 'Norwood Concert Hall',
  },
  {
    key: 4,
    date: '23 Nov 2022',
    city: 'MELBOURNE',
    venue: 'Hamer Hall',
  },
  {
    key: 5,
    date: '25 Nov 2022',
    city: 'CANBERRA',
    venue: 'The Playhouse',
  },
  {
    key: 6,
    date: '27 Nov 2022',
    city: 'BRISBANE',
    venue: 'The Tivoli',
  },
  {
    key: 6,
    date: '28 Nov 2022',
    city: 'BRISBANE',
    venue: 'The Tivoli',
  },
  {
    key: 8,
    date: '29 Nov 2022',
    city: 'SYDNEY',
    venue: 'Enmore Theatre',
  },
  {
    key: 9,
    date: '30 Nov 2022 ',
    city: 'SYDNEY',
    venue: 'Enmore Theatre',
  },
  {
    key: 10,
    date: '06 Dec 2022',
    city: 'WELLINGTON',
    venue: 'Opera House',
  },
  {
    key: 11,
    date: '07 Dec 2022',
    city: 'CHRISTCHURCH',
    venue: 'James Hay Theatre',
  },
  {
    key: 12,
    date: '08 Dec 2022',
    city: 'AUCKLAND',
    venue: 'Skycity Theatre',
  },
  {
    key: 13,
    date: '08 Dec 2022',
    city: 'AUCKLAND',
    venue: 'Skycity Theatre',
  },
  {
    key: 14,
    date: '30 Jan 2023',
    city: 'BARNASRD CASTLE',
    venue: 'The Witham',
  },
  {
    key: 15,
    date: '31 Jan 2023',
    city: 'HEXHAM',
    venue: 'Queen/’s Hall Arts Centre',
  },
  {
    key: 16,
    date: '01 Feb 2023 ',
    city: 'Northallerton',
    venue: 'The Forum',
  },
  {
    key: 17,
    date: '14 Feb 2023 ',
    city: 'Canterbury',
    venue: 'Marlowe Theatre',
  },
  {
    key: 18,
    date: '15 Feb 2023',
    city: 'Norwich',
    venue: 'Theatre Royal',
  },
  {
    key: 19,
    date: '18 Feb 2023',
    city: 'Edinburgh',
    venue: 'Queens Hall',
  },
  {
    key: 20,
    date: '25 Feb 2023 ',
    city: 'Portsmouth',
    venue: 'Kings Theatre',
  },
  {
    key: 21,
    date: '11 Apr 2023 ',
    city: 'Ipswich ',
    venue: 'Regent Theatre',
  },
  {
    key: 22,
    date: '12 Apr 2023',
    city: 'Brighton',
    venue: 'Dome',
  },
  {
    key: 23,
    date: '14 Apr 2023',
    city: 'Manchester',
    venue: 'AO Arena',
  },
  {
    key: 24,
    date: '19 Apr 2023',
    city: 'Nottingham',
    venue: 'Motorpoint Arena',
  },
  {
    key: 25,
    date: '20 Apr 2023',
    city: 'Cardiff',
    venue: 'Motorpoint Arena',
  },
  {
    key: 26,
    date: '21 Apr 2023',
    city: 'London',
    venue: 'O2',
  },
  {
    key: 28,
    date: '23 Apr 2023',
    city: 'London',
    venue: 'OVO Arena Wembley',
  },
  {
    key: 29,
    date: '28 Apr 2023',
    city: 'Birmingham',
    venue: 'Utilita Arena Birmingham',
  },
]
